version: '2'

services:
  testwebappbasic:
    image: testwebappbasic:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
